### ISSUE TITLE
Project python dependencies need to be installed in the ls environment

### ISSUE THREAD

**Issue by bartv** [inmanta/vscode-inmanta#65]
It seems that when you open a project that requires additional python dependencies the extension does not work. The compile will install the dependencies in the .env of the compiler like it should. However the LS will complain about not having these deps. This can be solved my manually installing them in the LS virtual env.

Potential cause: the LS does not activate the compiler generated virtual env?

(Not able to test on a clean install because of #63  and #64 )

Potentially a main.cf with `import aws` or `import openstack` is enough to reproduce this.

The logs show:

```
starting
Creating new virtual environment in /home/bart/workspace/projects/cloudbreakout/cbci_project/.env
verifying project
Compilation failed
Traceback (most recent call last):
  File "/home/bart/.config/Code/User/globalStorage/inmanta.inmanta/.env/lib64/python3.8/site-packages/inmanta/loader.py", line 303, in exec_module
    return super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bart/workspace/projects/cloudbreakout/cbci_project/libs/cbci/plugins/netbox.py", line 7, in <module>
    import pynetbox
ModuleNotFoundError: No module named 'pynetbox'
```

And the .env does contain it:
```
~/workspace/projects/cloudbreakout/cbci_project   master  .env/bin/pip list
Package               Version  
--------------------- ---------
bcrypt                3.2.0    
certifi               2020.11.8
cffi                  1.14.3   
chardet               3.0.4    
cryptography          3.1.1    
dataclasses           0.7      
future                0.18.2   
idna                  2.10     
importlib-resources   3.0.0    
Jinja2                2.11.2   
junos-eznc            2.5.3    
lxml                  4.5.2    
MarkupSafe            1.1.1    
ncclient              0.6.9    
ncdiff                20.10    
netaddr               0.8.0    
netmiko               3.3.2    
ntc-templates         1.5.0    
paramiko              2.7.2    
pip                   19.3.1   
pyang                 2.4.0    
pycparser             2.20     
PyNaCl                1.4.0    
pynetbox              5.1.0    
pyparsing             2.4.7    
pyserial              3.4      
PyYAML                5.3.1    
requests              2.25.0   
scp                   0.13.2   
setuptools            41.6.0   
six                   1.15.0   
tenacity              6.2.0    
textfsm               1.1.0    
transitions           0.8.3    
urllib3               1.26.2   
yamlordereddictloader 0.4.0    
zipp                  3.1.0   
```

**Comment by sanderr** [comment]
What inmanta version is running in the LS environment? It might be just an issue with incorrectly handling old compiler versions (that don't support specifying another venv than .env).

**Comment by bartv** [comment]
> What inmanta version is running in the LS environment? It might be just an issue with incorrectly handling old compiler versions (that don't support specifying another venv than .env).

```
/home/bart/.config/Code/User/globalStorage/inmanta.inmanta/.env/bin/pip list   Package                  Version                
------------------------ -----------------------
adal                     1.2.5                  
apipkg                   1.5                    
arrow                    0.17.0                 
asyncpg                  0.21.0                 
azure-common             1.1.26                 
azure-core               1.9.0                  
azure-identity           1.5.0                  
azure-mgmt-core          1.2.2                  
azure-mgmt-network       16.0.0                 
bcrypt                   3.2.0                  
binaryornot              0.4.4                  
boto3                    1.16.16                
botocore                 1.19.16                
cachetools               4.1.1                  
certifi                  2020.11.8              
cffi                     1.14.3                 
chardet                  3.0.4                  
click                    7.1.2                  
click-plugins            1.1.1                  
colorlog                 4.6.2                  
cookiecutter             1.7.2                  
cryptography             3.2.1                  
dnspython                2.0.0                  
docstring-parser         0.7.3                  
email-validator          1.1.2                  
execnet                  1.7.1                  
google-api-core          1.23.0                 
google-api-python-client 1.12.5                 
google-auth              1.23.0                 
google-auth-httplib2     0.0.4                  
googleapis-common-protos 1.52.0                 
httplib2                 0.18.1                 
idna                     2.10                   
importlib-metadata       2.0.0                  
inmanta                  2020.5                 
inmanta-license          1.2.2                  
inmanta-lsm              1.4.0                  
inmanta-support          1.2.1                  
inmantals                1.0.0                  
intervaltree             3.1.0                  
isodate                  0.6.0                  
Jinja2                   2.11.2                 
jinja2-time              0.2.0                  
jmespath                 0.10.0                 
lxml                     4.6.1                  
MarkupSafe               1.1.1                  
more-itertools           8.6.0                  
msal                     1.6.0                  
msal-extensions          0.3.0                  
msrest                   0.6.19                 
msrestazure              0.6.4                  
mypy-extensions          0.4.3                  
ncclient                 0.6.9                  
ncdiff                   2.1.3                  
netaddr                  0.8.0                  
netifaces                0.10.9                 
oauthlib                 3.1.0                  
paramiko                 2.7.2                  
pip                      19.3.1                 
ply                      3.11                   
portalocker              1.7.1                  
poyo                     0.5.0                  
protobuf                 3.13.0                 
psutil                   5.7.3                  
pyang                    2.4.0                  
pyasn1                   0.4.8                  
pyasn1-modules           0.2.8                  
pycparser                2.20                   
pydantic                 1.7.2                  
pyformance               0.4                    
PyJWT                    1.7.1                  
PyNaCl                   1.4.0                  
pynetbox                 5.1.0                  
pysirius                 1.0.9.dev20201104191332
python-dateutil          2.8.1                  
python-slugify           4.0.1                  
pytz                     2020.4                 
PyYAML                   5.3.1                  
requests                 2.25.0                 
requests-oauthlib        1.3.0                  
rsa                      4.6                    
s3transfer               0.3.3                  
setuptools               41.6.0                 
six                      1.15.0                 
sortedcontainers         2.3.0                  
text-unidecode           1.3                    
texttable                1.6.3                  
tinydb                   4.2.0                  
tornado                  6.1                    
typing-extensions        3.7.4.3                
typing-inspect           0.6.0                  
uritemplate              3.0.1                  
urllib3                  1.25.11                
zipp                     3.4.0
```

**Comment by sanderr** [comment]
I've encountered a similar issue when running the language server using `vim-lsp` on a project using the vyos module: "no module named pexpect". I assume this has the same cause but I haven't investigated further. I mention this because this might provide an easy reproduction. I encountered the issue both with the latest stable inmanta as with the current master.

**Comment by sanderr** [comment]
@bartv I can't say anything conclusively at the moment (I'm having trouble explaining the behavior I'm seeing with one of my existing venvs). Could you try removing the `.env` dir though? I seem to recall the reason we updated vscode to use a separate venv was to prevent issues such as this. Since core 2020.5 does not have support for this yet, isn't this a known issue?

**Comment by bartv** [comment]
I did a clean install on a virtual machine and except for ctrl+click not working plugins, it seems to work for complex modules there. I will remove my envs again and retry.

**Comment by bartv** [comment]
When I remove all virtual envs and clear the settings I managed to get it to work. This was with inmanta dev. I will try now with stable versions only

**Comment by bartv** [comment]
Without the dev version I am not able to get it to work. So that explains the issues

**Comment by sanderr** [comment]
- add README explaining the issue and how to deal with it
- create ticket to add a button to perform a cleanup.
